In [1]:
import pandas as pd
import numpy as np

# Series

In [2]:
obj = pd.Series([4, 7, -5, 3])

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
s = obj.index   # returns a range

In [6]:
s

RangeIndex(start=0, stop=4, step=1)

In [7]:
for i in s: 
    print(i)

0
1
2
3


In [8]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [9]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

#### Indexing

In [11]:
obj2['a']

-5

In [12]:
obj2['d'] = 6

In [13]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

#### Numpy-Like Operation
    # Using NumPy functions or NumPy-like operations, such as filtering with a boolean
    array, scalar multiplication, or applying math functions, will preserve the index-value
    link

In [14]:
obj2 > 0

d     True
b     True
a    False
c     True
dtype: bool

In [15]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [16]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [17]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [18]:
'b' in obj2

True

In [19]:
'e' in obj2

False

#### Series from python dictionary

In [20]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [21]:
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [22]:
obj3 = pd.Series(sdata)

In [23]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [24]:
obj3.index

Index(['Ohio', 'Texas', 'Oregon', 'Utah'], dtype='object')

In [25]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [26]:
obj4 = pd.Series(sdata, index=states)

In [27]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [28]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [29]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [30]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [31]:
obj4.name = 'Population'

In [32]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: Population, dtype: float64

In [33]:
obj4.index.name = 'state'

In [34]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: Population, dtype: float64

# DataFrame

In [35]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2],
       }

In [36]:
frame = pd.DataFrame(data)

In [37]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [38]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [39]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five', 'six'])

In [40]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [41]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [42]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [43]:
# Retrieving Columns

In [44]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [45]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [46]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [47]:
# Retriving Row

In [48]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [49]:
#Column Modifications

In [50]:
frame2['debt'] = 16.5

In [51]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [52]:
frame2['debt'] = np.arange(6.)

In [53]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [54]:
#Assigning series to a DataFrame

In [55]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [56]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [57]:
frame2['debt'] = val

In [58]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [59]:
# New Columns

In [60]:
frame2['eastern'] = frame2.state == 'Ohio'

In [61]:
frame2['western']= frame2['pop'] > 2.5

In [62]:
del frame2['eastern']

In [63]:
frame2

year   state  pop  debt  western
one    2000    Ohio  1.5   NaN    False
two    2001    Ohio  1.7  -1.2    False
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7     True
six    2003  Nevada  3.2   NaN     True

In [64]:
#nested dict of dict Frame

In [65]:
pop = {
    'Nevada': {2001: 2.4, 2002: 2.9},
    'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6},
} 

In [66]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [67]:
frame3 = pd.DataFrame(pop)

In [68]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [69]:
# Transposing

In [70]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [71]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [72]:
frame3.index.name = 'year'

In [73]:
frame3.columns.name = 'state'

In [74]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [75]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [76]:
frame3.index

Int64Index([2000, 2001, 2002], dtype='int64', name='year')

# Index Objects

In [77]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [78]:
obj

a    0
b    1
c    2
dtype: int64

In [79]:
index = obj.index

In [80]:
index

Index(['a', 'b', 'c'], dtype='object')

In [81]:
index[1:]

Index(['b', 'c'], dtype='object')

In [82]:
labels = pd.Index(np.arange(3))

In [83]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [84]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [85]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [86]:
obj2.index is labels

True

In [87]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [88]:
labels.append(labels)

Int64Index([0, 1, 2, 0, 1, 2], dtype='int64')

In [89]:
labels

Int64Index([0, 1, 2], dtype='int64')

# Reindexing

In [90]:
obj = pd.Series([4.5, 2.4, -4.2, 4.0, -6.3], index=['d', 'b', 'a', 'c', 'e'])

In [91]:
obj

d    4.5
b    2.4
a   -4.2
c    4.0
e   -6.3
dtype: float64

In [92]:
obj.reindex(['a', 'b', 'c','d', 'e', 'f'])

a   -4.2
b    2.4
c    4.0
d    4.5
e   -6.3
f    NaN
dtype: float64

In [93]:
# ffill()

In [94]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=range(0, 5, 2))

In [95]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [96]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

Reindexing with Dataframe

In [97]:
frame = pd.DataFrame(np.arange(9).reshape(3, 3), index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])

In [98]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [99]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [100]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [101]:
#Reindexing Columns

In [102]:
states = ['Texas', 'Utah', 'California']

In [103]:
frame2.reindex(columns=states)

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

# Drop entries from an axis

In [104]:
obj = pd.Series(np.arange(6.), index=['a', 'b', 'c', 'd', 'e', 'f'])

In [105]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
f    5.0
dtype: float64

In [106]:
new_obj = obj.drop('f')

In [107]:
new_obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [108]:
new_obj = new_obj.drop(['c', 'd'])

In [109]:
new_obj

a    0.0
b    1.0
e    4.0
dtype: float64

### Droping entries in dataframe

In [110]:
data = pd.DataFrame(np.arange(16).reshape(4, 4), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])

In [111]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

From Axis 0

In [112]:
data.drop('Ohio')

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [113]:
data.drop(['Ohio', 'Utah'])

one  two  three  four
Colorado    4    5      6     7
New York   12   13     14    15

From Axis 1

In [114]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [115]:
data.drop('one', axis=1)

two  three  four
Ohio        1      2     3
Colorado    5      6     7
Utah        9     10    11
New York   13     14    15

In [116]:
data.drop(['one', 'two', 'four'], axis=1)

three
Ohio          2
Colorado      6
Utah         10
New York     14

In [117]:
data.name = 'Co'

# Indexing, Selection and Filtering

In [118]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [119]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [120]:
obj[1]

1.0

In [121]:
obj[2]

2.0

In [122]:
obj['a']

0.0

In [123]:
obj['b']

1.0

In [124]:
obj[1:4]

b    1.0
c    2.0
d    3.0
dtype: float64

In [125]:
obj[[1, 3, 2]]

b    1.0
d    3.0
c    2.0
dtype: float64

In [126]:
obj['b': 'c']

b    1.0
c    2.0
dtype: float64

In [127]:
obj > 2

a    False
b    False
c    False
d     True
dtype: bool

In [128]:
obj[obj > 2]

d    3.0
dtype: float64

In [129]:
obj['b': 'c'] = 5

In [130]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [131]:
obj[['a', 'd']] = 3.7

In [132]:
obj

a    3.7
b    5.0
c    5.0
d    3.7
dtype: float64

Indexing for DataFrame

In [133]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [134]:
data['one']

Ohio         0
Colorado     4
Utah         8
New York    12
Name: one, dtype: int32

In [135]:
data[['one', 'four']]

one  four
Ohio        0     3
Colorado    4     7
Utah        8    11
New York   12    15

In [136]:
data.one

Ohio         0
Colorado     4
Utah         8
New York    12
Name: one, dtype: int32

In [137]:
data[0:3]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11

In [138]:
data > 5

one    two  three   four
Ohio      False  False  False  False
Colorado  False  False   True   True
Utah       True   True   True   True
New York   True   True   True   True

In [139]:
data[data <= 5]

one  two  three  four
Ohio      0.0  1.0    2.0   3.0
Colorado  4.0  5.0    NaN   NaN
Utah      NaN  NaN    NaN   NaN
New York  NaN  NaN    NaN   NaN

Selection with loc and iloc

In [140]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [141]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [142]:
data.loc[['Ohio', 'Utah'], 'one']

Ohio    0
Utah    8
Name: one, dtype: int32

In [143]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [144]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [145]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    4    5
Utah        11    8    9

In [146]:
data.loc[:'Utah', 'two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int32

In [147]:
data.iloc[:, :3]

one  two  three
Ohio        0    1      2
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [148]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

# Arithematic and Data Alignment

In [149]:
s1 = pd.Series([2.3, 5.2, 1.4, -3.4], index=['a', 'c', 'd', 'e'])

In [150]:
s1

a    2.3
c    5.2
d    1.4
e   -3.4
dtype: float64

In [151]:
s2 = pd.Series([-2.3, 1.3, -5.2, 3.6, 3.6], index=['a', 'c', 'e', 'f', 'g'])

In [152]:
s2

a   -2.3
c    1.3
e   -5.2
f    3.6
g    3.6
dtype: float64

In [153]:
s1 + s2

a    0.0
c    6.5
d    NaN
e   -8.6
f    NaN
g    NaN
dtype: float64

### For DataFrames

In [154]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), index=['Ohio', 'Texas', 'Colorado'], columns=list('bcd'))

In [155]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [156]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), index=['Utah', 'Ohio', 'Texas', 'Oregon'], columns=list('bde'))

In [157]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [158]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [159]:
df1 = pd.DataFrame({'A': [1, 2]}, index=['a', 'b'])

In [160]:
df1

A
a  1
b  2

In [161]:
df2 = pd.DataFrame({'A': [3, 4]}, index=['a', 'c'])

In [162]:
df2

A
a  3
c  4

In [163]:
df1 + df2

A
a  4.0
b  NaN
c  NaN

### Arithmetic methods with fill values

In [164]:
df1 = pd.DataFrame(np.arange(12.).reshape(3, 4), columns=list('abcd'))

In [165]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [166]:
df2 = pd.DataFrame(np.arange(20.).reshape(4, 5), columns=list('abcde'))

In [167]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [168]:
df2.loc[1, 'b'] = np.nan

In [169]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [170]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [171]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [172]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [173]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

# Operations between DataFrame and Series

In [174]:
arr = np.arange(12.).reshape(3, 4)

In [175]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [176]:
arr[0]

array([0., 1., 2., 3.])

In [177]:
# BROADCASTING
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [178]:
arr[0] - arr

array([[ 0.,  0.,  0.,  0.],
       [-4., -4., -4., -4.],
       [-8., -8., -8., -8.]])

#### Operations between a DataFrame and a Series are similar

In [179]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
.....: columns=list('bde'),
.....: index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [180]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [181]:
series = frame.iloc[0]

In [182]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [183]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [184]:
series2 = pd.Series(np.arange(3), index=['b', 'e', 'f'])

In [185]:
series2

b    0
e    1
f    2
dtype: int32

In [187]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

# Function Application and Mapping 

In [201]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [202]:
frame

b         d         e
Utah    0.691569  0.936047 -1.486726
Ohio    0.617759 -0.717662 -1.103583
Texas  -0.429923 -1.080791 -0.135295
Oregon  2.581646  0.975369 -1.710133

In [212]:
frame = np.abs(frame)
frame

b         d         e
Utah    0.691569  0.936047  1.486726
Ohio    0.617759  0.717662  1.103583
Texas   0.429923  1.080791  0.135295
Oregon  2.581646  0.975369  1.710133

In [213]:
f = lambda x: x.max() - x.min()

In [214]:
frame.apply(f)

b    2.151723
d    0.363129
e    1.574838
dtype: float64

In [217]:
frame.apply(f, axis=1)

Utah      0.795157
Ohio      0.485824
Texas     0.945496
Oregon    1.606276
dtype: float64

### Series with multiple scalar values

In [222]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [225]:
frame.apply(f)

b         d         e
min  0.429923  0.717662  0.135295
max  2.581646  1.080791  1.710133

In [226]:
frame.apply(f, axis='columns')

min       max
Utah    0.691569  1.486726
Ohio    0.617759  1.103583
Texas   0.135295  1.080791
Oregon  0.975369  2.581646

#### applymap

In [231]:
format = lambda x: '%.2f' % x

In [232]:
frame.applymap(format)

b     d     e
Utah    0.69  0.94  1.49
Ohio    0.62  0.72  1.10
Texas   0.43  1.08  0.14
Oregon  2.58  0.98  1.71

In [234]:
frame['b'].map(format)

Utah      0.69
Ohio      0.62
Texas     0.43
Oregon    2.58
Name: b, dtype: object