In [1]:
import numpy as np

# Checking Numpy Array vs Python List Efficiency

In [2]:
lst = list(range(1000000))

In [3]:
arr = np.arange(1000000)

In [4]:
# Checking Python list efficicency by multiplying each number in list by 2 10 times.
%time for i in range(10): lst2 = [p * 2 for p in lst]

Wall time: 3.7 s


In [5]:
# Checking Numpy efficicency by multiplying each number in array by 2 10 times.
%time for i in range(10): arr2 = arr * 2

Wall time: 80.1 ms


# Creating an array and multiplying with scalar element

In [6]:
# Generating some random data.
data = np.random.randn(2, 3)

In [7]:
data

array([[-0.64213707,  0.49590477, -0.90128904],
       [-0.19946456,  0.51801786,  1.24983828]])

In [8]:
data * 10  # it will multiply each element in array by 10 without writing any for loop.

array([[-6.42137067,  4.9590477 , -9.01289042],
       [-1.99464563,  5.18017857, 12.49838282]])

In [9]:
data + data   # All the element in data are added to each corresponding cell in the array.

array([[-1.28427413,  0.99180954, -1.80257808],
       [-0.39892913,  1.03603571,  2.49967656]])

# Array Shape And Dtype

In [10]:
# Indicate how many rows and columns in the array, in this case 2 rows and 3 columns.
data.shape

(2, 3)

In [11]:
# Indicate the array data type, in this case float.
data.dtype

dtype('float64')

# Creating ndarray

In [12]:
# The easiest way to create an array is to pass list to array function.
data1 = [6, 7.5, 1, 8, 2]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 1. , 8. , 2. ])

In [13]:
# Passing nested lists of equal length will create a multidimensional array.
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
# To check is it really a multidimensional array, we use ndim.
arr2.ndim

2

In [15]:
arr2.shape

(2, 4)

# Other ways for creating ndarray or Numpy Array

In [16]:
# Creating array of zeros.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
# Pass a shape for higher dimensions.
np.zeros((2, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
# Creating array of ones.
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
data3 = np.ones((3, 2, 3))
data3

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [20]:
data3.ndim

3

In [21]:
# Creating array empty elements. -> It’s not safe to assume that np.empty will return an array of all
#zeros. In some cases, it may return uninitialized “garbage” values.
np.empty((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
# Generating series of numbers.
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Datatypes for ndarray

In [24]:
# dtype is a special object containing information about ndarray.
arr1 = np.array([1, 2, 3, 4], dtype=np.float64)

In [25]:
arr1

array([1., 2., 3., 4.])

In [26]:
arr2 = np.array([1., 2., 3., 4.], dtype=np.int32)

In [27]:
arr2

array([1, 2, 3, 4])

In [28]:
arr1.dtype

dtype('float64')

In [29]:
arr2.dtype

dtype('int32')

In [30]:
# CASTING using numpy ---- astype method ------

In [31]:
arr = np.array([1, 2, 3, 4])

In [32]:
arr.dtype

dtype('int32')

In [33]:
float_arr = arr.astype(np.float64)

In [34]:
float_arr

array([1., 2., 3., 4.])

In [35]:
float_arr.dtype

dtype('float64')

In [36]:
arr = np.array([2.3, 4.2, 5.3, 6.2, 1.9, 4.5, 1.0])

In [37]:
arr.dtype

dtype('float64')

In [38]:
int_arr = arr.astype(np.int32)

In [39]:
int_arr

array([2, 4, 5, 6, 1, 4, 1])

In [40]:
int_arr.dtype

dtype('int32')

In [41]:
# Converting Strings to floats
string_arr = np.array(['3.4', '-2.3', '4.5', '8', '3.8', '5.2', '3.7'], dtype=np.string_)

In [42]:
string_arr

array([b'3.4', b'-2.3', b'4.5', b'8', b'3.8', b'5.2', b'3.7'], dtype='|S4')

In [43]:
string_arr.dtype

dtype('S4')

In [44]:
float_arr = string_arr.astype(np.float64)

In [45]:
float_arr

array([ 3.4, -2.3,  4.5,  8. ,  3.8,  5.2,  3.7])

In [46]:
float_arr.dtype

dtype('float64')

# Arithematic with Numpy Arrays

In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)

In [48]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [49]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [50]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
# Arithematic operations with scalar propagates scalar to each element in array.
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [52]:
arr * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [53]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [54]:
# Comparison
# Comparison between arrays of same size yields boolean arrays.

In [55]:
arr1 = np.array([[0, 4, 1], [7, 2, 12]], dtype=np.float64)

In [56]:
arr1

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [57]:
bool_arr = arr1 > arr

In [58]:
bool_arr

array([[False,  True, False],
       [ True, False,  True]])

In [59]:
bool_arr.dtype

dtype('bool')

# Indexing And Slicing

In [60]:
arr = np.arange(10)

In [61]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr[5]

5

In [63]:
arr[5:8]

array([5, 6, 7])

In [64]:
arr[5:8] = 12

In [65]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [66]:
# SLCING IN ARRAYS ARE VIEWS.
arr_slice = arr[5:8]

In [67]:
arr_slice

array([12, 12, 12])

In [68]:
arr_slice[1] = 12345

In [69]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [70]:
arr_slice

array([   12, 12345,    12])

HIGHER DIMENSIONS INDEXING

In [71]:
arr2d = np.array([[1, 2, 3, 4], [3, 5, 2, 5]])

In [72]:
arr2d[1]

array([3, 5, 2, 5])

In [73]:
arr2d[1][3]

5

In [74]:
arr2d[1, 3]

5

3D Array

In [75]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [76]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
old_values = arr3d[0].copy()

In [78]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [80]:
arr3d[0] = 42

In [81]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [82]:
arr3d[0] = old_values

In [83]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Indexing with slices

In [84]:
arr = np.arange(15)

In [85]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [86]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [87]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [88]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [91]:
arr2d[1, :2]

array([4, 5])

In [92]:
arr2d[:2,2]

array([3, 6])

In [93]:
arr2d[:2, 2]

array([3, 6])

Boolean Indexing

In [94]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [95]:
data = np.random.randn(7, 4)

In [96]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [97]:
data

array([[-0.81976328,  0.9959895 , -2.01570903,  0.8757738 ],
       [-0.70868852,  0.94748944,  0.94937647, -0.53474265],
       [-0.62620949, -0.28616129, -1.0675595 ,  1.17121998],
       [-0.01562426, -0.14060872,  1.51227298, -0.07705517],
       [ 0.19920905, -0.40880573, -0.33506916, -2.52778123],
       [-0.38352831, -2.27283382, -0.01613411,  1.21932205],
       [-1.49161824,  2.06119664,  1.35024007,  0.45770626]])

In [98]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [99]:
data[names == 'Bob']

array([[-0.81976328,  0.9959895 , -2.01570903,  0.8757738 ],
       [-0.01562426, -0.14060872,  1.51227298, -0.07705517]])

In [100]:
data[names == 'Bob', 2:]

array([[-2.01570903,  0.8757738 ],
       [ 1.51227298, -0.07705517]])

In [101]:
data[names == 'Bob', 3]

array([ 0.8757738 , -0.07705517])

In [102]:
data[~(names == 'Bob')]

array([[-0.70868852,  0.94748944,  0.94937647, -0.53474265],
       [-0.62620949, -0.28616129, -1.0675595 ,  1.17121998],
       [ 0.19920905, -0.40880573, -0.33506916, -2.52778123],
       [-0.38352831, -2.27283382, -0.01613411,  1.21932205],
       [-1.49161824,  2.06119664,  1.35024007,  0.45770626]])

In [103]:
data[names != 'Bob']

array([[-0.70868852,  0.94748944,  0.94937647, -0.53474265],
       [-0.62620949, -0.28616129, -1.0675595 ,  1.17121998],
       [ 0.19920905, -0.40880573, -0.33506916, -2.52778123],
       [-0.38352831, -2.27283382, -0.01613411,  1.21932205],
       [-1.49161824,  2.06119664,  1.35024007,  0.45770626]])

In [104]:
data[names == 'Bob'] = 7.0

In [105]:
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.70868852,  0.94748944,  0.94937647, -0.53474265],
       [-0.62620949, -0.28616129, -1.0675595 ,  1.17121998],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.19920905, -0.40880573, -0.33506916, -2.52778123],
       [-0.38352831, -2.27283382, -0.01613411,  1.21932205],
       [-1.49161824,  2.06119664,  1.35024007,  0.45770626]])

In [106]:
data[names != 'Bob'] = 0.0

In [107]:
data

array([[7., 7., 7., 7.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [7., 7., 7., 7.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [108]:
cond = names == 'Bob'

In [109]:
cond

array([ True, False, False,  True, False, False, False])

In [110]:
data[~cond]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Fancy Indexing 

In [111]:
arr = np.empty((8, 4))

In [112]:
for i in range(8):
    arr[i] = i

In [113]:
for i in arr:
    print(i)

[0. 0. 0. 0.]
[1. 1. 1. 1.]
[2. 2. 2. 2.]
[3. 3. 3. 3.]
[4. 4. 4. 4.]
[5. 5. 5. 5.]
[6. 6. 6. 6.]
[7. 7. 7. 7.]


In [114]:
arr[[3, 2, 7, 6]]

array([[3., 3., 3., 3.],
       [2., 2., 2., 2.],
       [7., 7., 7., 7.],
       [6., 6., 6., 6.]])

In [115]:
arr[[-1, 2, -8]]

array([[7., 7., 7., 7.],
       [2., 2., 2., 2.],
       [0., 0., 0., 0.]])

Passing Multiple Index Arrays

In [116]:
arr = np.arange(32).reshape((8, 4))

In [117]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [118]:
arr[[3, 4, 1], [3, 1, 0]]

array([15, 17,  4])

In [119]:
# NEEEED TO UNDERSTAND
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# TRANSPOSING ARRAYS AND SWAPPING AXES

In [120]:
arr = np.arange(15).reshape(3, 5)

In [121]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [122]:
a = arr.T

In [123]:
a[1:-1, 1:] = 0

In [124]:
a

array([[ 0,  5, 10],
       [ 1,  0,  0],
       [ 2,  0,  0],
       [ 3,  0,  0],
       [ 4,  9, 14]])

In [125]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  0,  0,  0,  9],
       [10,  0,  0,  0, 14]])

In [126]:
arr = np.arange(16).reshape(2, 2, 4)

In [127]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [128]:
arr.transpose(1, 0, 2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [129]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [130]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

# Universal Functions: Fast Element-Wise Array Functions

In [131]:
arr = np.arange(10)

In [132]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [134]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [135]:
a = np.random.randn(8)

In [136]:
b = np.random.randn(8)

In [137]:
a

array([ 0.60688164, -0.74528007,  1.52843019,  0.44164744, -1.60485187,
       -0.23385852,  0.61032562, -1.12909774])

In [138]:
b

array([ 0.97802666, -1.06090808,  0.1571179 ,  0.55821011, -2.26064864,
       -0.4800681 , -0.93588666,  0.79475949])

In [139]:
np.add(a, b)

array([ 1.5849083 , -1.80618815,  1.68554809,  0.99985756, -3.86550051,
       -0.71392662, -0.32556104, -0.33433825])

In [140]:
np.maximum(a, b)

array([ 0.97802666, -0.74528007,  1.52843019,  0.55821011, -1.60485187,
       -0.23385852,  0.61032562,  0.79475949])

In [141]:
arr = np.arange(10)

In [151]:
a, b = np.modf?

In [ ]:
a, b = np.modf

In [152]:
a, b = np.modf(arr)

In [153]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [154]:
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# Expressing Conditional Logic as Array Operations

In [155]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [156]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [157]:
cond = np.array([True, False, True, True, False])

In [158]:
# np.Where

In [159]:
result = np.where(cond, xarr, yarr)

In [160]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [161]:
# use of np.where

In [162]:
arr = np.random.randn(4, 4)

In [163]:
arr

array([[-1.12466719, -0.2437096 ,  2.33517197,  0.68427773],
       [-0.35474677, -0.68805194, -0.39086932, -0.47629785],
       [ 2.18307436, -0.93053544, -0.66437129, -0.21364757],
       [ 0.29343822,  0.87586205, -0.27036821, -0.30166494]])

In [164]:
arr > 0

array([[False, False,  True,  True],
       [False, False, False, False],
       [ True, False, False, False],
       [ True,  True, False, False]])

In [165]:
arr < 0

array([[ True,  True, False, False],
       [ True,  True,  True,  True],
       [False,  True,  True,  True],
       [False, False,  True,  True]])

In [166]:
result = np.where(arr > 0, 2, -2)

In [167]:
result

array([[-2, -2,  2,  2],
       [-2, -2, -2, -2],
       [ 2, -2, -2, -2],
       [ 2,  2, -2, -2]])

# Mathematical and Statistical methods

In [168]:
arr = np.random.randn(5, 4)

In [169]:
arr

array([[ 0.96058711, -0.47166116,  0.38959339,  1.0889096 ],
       [ 0.75590228, -0.22200178,  0.49658843,  1.055667  ],
       [ 0.19633598, -0.32576505,  1.88747176,  0.7249604 ],
       [ 0.93703719,  0.99756608,  1.05226362, -0.35026875],
       [-0.24455009,  0.51270922, -0.40324866, -0.49739057]])

In [170]:
np.sum(arr)

8.540706015740742

In [171]:
a = np.arange(10).reshape(5, 2)

In [172]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [173]:
np.mean(a)

4.5

In [174]:
arr

array([[ 0.96058711, -0.47166116,  0.38959339,  1.0889096 ],
       [ 0.75590228, -0.22200178,  0.49658843,  1.055667  ],
       [ 0.19633598, -0.32576505,  1.88747176,  0.7249604 ],
       [ 0.93703719,  0.99756608,  1.05226362, -0.35026875],
       [-0.24455009,  0.51270922, -0.40324866, -0.49739057]])

In [175]:
np.mean(arr)

0.4270353007870371

In [176]:
np.std(a)

2.8722813232690143

In [177]:
np.var(a)

8.25

In [178]:
np.min(a)

0

In [179]:
np.max(a)

9

In [180]:
np.min(arr)

-0.4973905729643297

In [181]:
np.max(arr)

1.887471762734624

In [182]:
np.argmin(a)

0

In [183]:
np.argmax(a)

9

In [184]:
np.argmin(arr)

19

In [185]:
np.argmax(arr)

10

In [186]:
np.cumsum(a)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [187]:
np.cumsum(arr)

array([0.96058711, 0.48892596, 0.87851935, 1.96742895, 2.72333122,
       2.50132945, 2.99791788, 4.05358489, 4.24992087, 3.92415581,
       5.81162758, 6.53658797, 7.47362516, 8.47119124, 9.52345486,
       9.17318611, 8.92863603, 9.44134525, 9.03809659, 8.54070602])

In [188]:
np.cumprod(a)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [189]:
np.cumprod(arr)

array([ 9.60587112e-01, -4.53071628e-01, -1.76513713e-01, -1.92207476e-01,
       -1.45290069e-01,  3.22546533e-02,  1.60172877e-02,  1.69089222e-02,
        3.31982984e-03, -1.08148455e-03, -2.04127154e-03, -1.47984103e-03,
       -1.38666607e-03, -1.38329104e-03, -1.45558684e-03,  5.09846581e-04,
       -1.24683025e-04, -6.39261358e-05,  2.57781284e-05, -1.28217980e-05])

In [190]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [191]:
np.sum(a, axis=0)

array([20, 25])

In [192]:
np.mean(arr, 1)

array([ 0.49185724,  0.52153898,  0.62075077,  0.65914954, -0.15812002])

In [193]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [194]:
a.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [195]:
a.cumsum(1)

array([[ 0,  1],
       [ 2,  5],
       [ 4,  9],
       [ 6, 13],
       [ 8, 17]], dtype=int32)

In [196]:
a.sum(0)

array([20, 25])

In [197]:
np.sum(a, axis=1)

array([ 1,  5,  9, 13, 17])

In [198]:
a.sum(0)

array([20, 25])

In [199]:
a.mean(1)

array([0.5, 2.5, 4.5, 6.5, 8.5])

# Methods for Boolean Arrays

In [200]:
arr = np.random.randn(100)

In [201]:
arr

array([-1.75035842e-01,  4.21727620e-01,  3.55450487e-01, -6.99401212e-01,
       -5.98157919e-02, -6.50982853e-01,  5.67684509e-01, -3.10500410e-01,
       -1.62443864e-01,  1.26779538e+00, -8.68795079e-01,  1.09780011e+00,
        4.06885575e-01, -3.64618416e-01, -3.52575428e-02, -8.21096331e-01,
       -1.20040934e+00,  4.80332169e-01, -3.22264472e-02, -2.04742848e+00,
       -4.68022135e-01, -2.03541141e+00, -4.35897519e-01,  4.60523764e-01,
        1.89991489e-01, -4.81791243e-01,  1.57715513e+00, -4.36274684e-01,
        1.82666925e-01,  1.02351853e+00, -4.47862397e-01,  1.71225234e+00,
       -1.54709364e+00,  1.52071737e-01,  1.55400304e+00,  9.63507099e-01,
        1.19221560e+00,  6.31187696e-01, -3.04991756e-01,  3.37405969e+00,
        8.66402050e-01, -1.89268463e-01,  1.15699149e+00,  2.22459575e-01,
        2.41234316e-01, -6.54431635e-01,  1.92765301e+00, -6.11280417e-01,
        7.49595379e-03, -3.57502403e-01,  5.45057590e-01,  1.82761477e+00,
        1.20771070e+00, -

In [202]:
b = arr[arr > 0]

In [203]:
len(b)

57

In [204]:
arr[arr > 0].sum()

47.90468421528051

In [205]:
(arr > 0).sum()

57

In [206]:
arr[arr > 0].sum()

47.90468421528051

In [207]:
a = np.array([3, 4, -2, 2, 1, 4, -2])

In [208]:
a

array([ 3,  4, -2,  2,  1,  4, -2])

In [209]:
a > 0

array([ True,  True, False,  True,  True,  True, False])

In [210]:
a[a > 0]

array([3, 4, 2, 1, 4])

In [211]:
a[a > 0].sum()

14

In [212]:
(a > 0).sum()

5

In [213]:
(a > 0).any()

True

In [214]:
(a > 0).all()

False

Sorting

In [215]:
arr = np.array([4, 2, 1, 0, 6, 3])

In [216]:
arr

array([4, 2, 1, 0, 6, 3])

In [217]:
arr.sort()

In [218]:
arr

array([0, 1, 2, 3, 4, 6])

In [219]:
a = np.random.randn(5, 3)

In [220]:
a

array([[-0.72251618, -1.01552663,  0.762251  ],
       [-0.44971928,  0.53631825,  1.90509247],
       [-1.28762689, -1.36047361,  0.72615172],
       [-1.39467113, -1.40028504, -2.1442903 ],
       [-0.3235553 , -1.41634825, -1.08870079]])

In [221]:
a.sort(0)

In [222]:
a

array([[-1.39467113, -1.41634825, -2.1442903 ],
       [-1.28762689, -1.40028504, -1.08870079],
       [-0.72251618, -1.36047361,  0.72615172],
       [-0.44971928, -1.01552663,  0.762251  ],
       [-0.3235553 ,  0.53631825,  1.90509247]])

# Unique and Other Set Logic

In [223]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [224]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [225]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [226]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [227]:
ints

array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [228]:
np.unique(ints)

array([1, 2, 3, 4])

In [229]:
arr = np.arange(15)

# File Input and Output with Arrays

In [230]:
np.save('testarray', arr)

In [231]:
np.load('testarray.npy')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Linear Algebra

In [235]:
a = np.arange(1, 7).reshape(2, 3)

In [236]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [240]:
b = np.array([[6, 23], [-1, 7], [8, 9]])

In [241]:
b

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [244]:
np.dot(a, b)

array([[ 28,  64],
       [ 67, 181]])

matrix product between a two-dimensional array and a suitably sized onedimensional
array results in a one-dimensional array

In [246]:
np.dot(a, np.ones(3))

array([ 6., 15.])

In [247]:
np.ones(3)

array([1., 1., 1.])

In [248]:
a @ b

array([[ 28,  64],
       [ 67, 181]])

numpy.linalg 

In [283]:
from numpy.linalg import inv, qr, det

In [262]:
X = np.arange(1, 26).reshape(5, 5)

In [263]:
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [265]:
mat = X.T.dot(X)

In [266]:
mat

array([[ 855,  910,  965, 1020, 1075],
       [ 910,  970, 1030, 1090, 1150],
       [ 965, 1030, 1095, 1160, 1225],
       [1020, 1090, 1160, 1230, 1300],
       [1075, 1150, 1225, 1300, 1375]])

In [267]:
inv(mat)

array([[-1.61261705e+13,  8.79609302e+12,  1.68591783e+13,
         4.39804651e+12, -1.39271473e+13],
       [ 1.46601550e+13, -8.79609302e+12, -1.61261705e+13,
         3.35937500e-03,  1.02621085e+13],
       [ 5.86406201e+12, -0.00000000e+00, -7.33007752e+12,
        -8.79609302e+12,  1.02621085e+13],
       [ 8.79609302e+12, -8.79609302e+12, -4.39804651e+12,
        -0.00000000e+00,  4.39804651e+12],
       [-1.31941395e+13,  8.79609302e+12,  1.09951163e+13,
         4.39804651e+12, -1.09951163e+13]])

In [268]:
mat.dot(inv(mat))

array([[ 2.,  0., -4., -1.,  0.],
       [ 4.,  0., -4.,  0.,  2.],
       [ 4.,  0., -4., -1.,  4.],
       [ 2.,  0., -2., -1.,  4.],
       [ 0.,  0., -2.,  0.,  4.]])

In [269]:
q, r = qr(mat)

In [270]:
r

array([[-2.16480369e+03, -2.31094858e+03, -2.45709347e+03,
        -2.60323836e+03, -2.74938325e+03],
       [ 0.00000000e+00,  4.08297289e+00,  8.16594578e+00,
         1.22489187e+01,  1.63318916e+01],
       [ 0.00000000e+00,  0.00000000e+00, -1.26658883e-13,
        -1.15882484e-13, -1.43937555e-13],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         2.97663078e-13,  2.72066977e-13],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -1.07281270e-13]])

In [271]:
# diag

In [272]:
a = np.eye(5, 5)

In [273]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [275]:
b = np.diag(a)

In [276]:
b

array([1., 1., 1., 1., 1.])

In [286]:
np.diag(b)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [287]:
# trace

In [288]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [289]:
np.trace(a)

5.0

In [290]:
det(a)

1.0

# Pseudorandom Number Generation

In [298]:
samples = np.random.normal(size=(4, 4))

In [299]:
samples

array([[ 0.96778204, -0.71989191, -0.26067494, -0.19155625],
       [ 0.66561974,  0.43800947,  0.1798425 ,  0.80902993],
       [-0.65190641, -1.78171258, -0.81085111,  0.41094963],
       [ 0.56622068,  0.80773732, -0.18648851,  0.18454017]])

# Python Built-in random module vs numpy.random module

In [300]:
from random import normalvariate

In [301]:
N = 1000000

In [308]:
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

3.65 s ± 143 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [307]:
%timeit np.random.normal(size=N)

112 ms ± 3.89 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
