In [1]:
import numpy as np

# Checking Numpy Array vs Python List Efficiency

In [2]:
lst = list(range(1000000))

In [3]:
arr = np.arange(1000000)

In [4]:
# Checking Python list efficicency by multiplying each number in list by 2 10 times.
%time for i in range(10): lst2 = [p * 2 for p in lst]

Wall time: 3.09 s


In [5]:
# Checking Numpy efficicency by multiplying each number in array by 2 10 times.
%time for i in range(10): arr2 = arr * 2

Wall time: 73 ms


# Creating an array and multiplying with scalar element

In [6]:
# Generating some random data.
data = np.random.randn(2, 3)

In [7]:
data

array([[-0.95824244,  0.80958177, -0.18465733],
       [-0.29095473,  0.37608253,  0.46419995]])

In [8]:
data * 10  # it will multiply each element in array by 10 without writing any for loop.

array([[-9.58242437,  8.09581769, -1.84657332],
       [-2.90954728,  3.76082527,  4.64199949]])

In [9]:
data + data   # All the element in data are added to each corresponding cell in the array.

array([[-1.91648487,  1.61916354, -0.36931466],
       [-0.58190946,  0.75216505,  0.9283999 ]])

# Array Shape And Dtype

In [10]:
# Indicate how many rows and columns in the array, in this case 2 rows and 3 columns.
data.shape

(2, 3)

In [11]:
# Indicate the array data type, in this case float.
data.dtype

dtype('float64')

# Creating ndarray

In [12]:
# The easiest way to create an array is to pass list to array function.
data1 = [6, 7.5, 1, 8, 2]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 1. , 8. , 2. ])

In [13]:
# Passing nested lists of equal length will create a multidimensional array.
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
# To check is it really a multidimensional array, we use ndim.
arr2.ndim

2

In [15]:
arr2.shape

(2, 4)

# Other ways for creating ndarray or Numpy Array

In [16]:
# Creating array of zeros.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
# Pass a shape for higher dimensions.
np.zeros((2, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
# Creating array of ones.
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
data3 = np.ones((3, 2, 3))
data3

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [20]:
data3.ndim

3

In [21]:
# Creating array empty elements. -> It’s not safe to assume that np.empty will return an array of all
#zeros. In some cases, it may return uninitialized “garbage” values.
np.empty((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
# Generating series of numbers.
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Datatypes for ndarray

In [24]:
# dtype is a special object containing information about ndarray.
arr1 = np.array([1, 2, 3, 4], dtype=np.float64)

In [25]:
arr1

array([1., 2., 3., 4.])

In [26]:
arr2 = np.array([1., 2., 3., 4.], dtype=np.int32)

In [27]:
arr2

array([1, 2, 3, 4])

In [28]:
arr1.dtype

dtype('float64')

In [29]:
arr2.dtype

dtype('int32')

In [30]:
# CASTING using numpy ---- astype method ------

In [31]:
arr = np.array([1, 2, 3, 4])

In [32]:
arr.dtype

dtype('int32')

In [33]:
float_arr = arr.astype(np.float64)

In [34]:
float_arr

array([1., 2., 3., 4.])

In [35]:
float_arr.dtype

dtype('float64')

In [36]:
arr = np.array([2.3, 4.2, 5.3, 6.2, 1.9, 4.5, 1.0])

In [37]:
arr.dtype

dtype('float64')

In [38]:
int_arr = arr.astype(np.int32)

In [39]:
int_arr

array([2, 4, 5, 6, 1, 4, 1])

In [40]:
int_arr.dtype

dtype('int32')

In [41]:
# Converting Strings to floats
string_arr = np.array(['3.4', '-2.3', '4.5', '8', '3.8', '5.2', '3.7'], dtype=np.string_)

In [42]:
string_arr

array([b'3.4', b'-2.3', b'4.5', b'8', b'3.8', b'5.2', b'3.7'], dtype='|S4')

In [43]:
string_arr.dtype

dtype('S4')

In [44]:
float_arr = string_arr.astype(np.float64)

In [45]:
float_arr

array([ 3.4, -2.3,  4.5,  8. ,  3.8,  5.2,  3.7])

In [46]:
float_arr.dtype

dtype('float64')

# Arithematic with Numpy Arrays

In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)

In [48]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [49]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [50]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
# Arithematic operations with scalar propagates scalar to each element in array.
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [52]:
arr * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [53]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [54]:
# Comparison
# Comparison between arrays of same size yields boolean arrays.

In [55]:
arr1 = np.array([[0, 4, 1], [7, 2, 12]], dtype=np.float64)

In [56]:
arr1

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [57]:
bool_arr = arr1 > arr

In [58]:
bool_arr

array([[False,  True, False],
       [ True, False,  True]])

In [59]:
bool_arr.dtype

dtype('bool')

# Indexing And Slicing

In [60]:
arr = np.arange(10)

In [61]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr[5]

5

In [63]:
arr[5:8]

array([5, 6, 7])

In [64]:
arr[5:8] = 12

In [65]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [66]:
# SLCING IN ARRAYS ARE VIEWS.
arr_slice = arr[5:8]

In [67]:
arr_slice

array([12, 12, 12])

In [68]:
arr_slice[1] = 12345

In [69]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [70]:
arr_slice

array([   12, 12345,    12])

HIGHER DIMENSIONS INDEXING

In [71]:
arr2d = np.array([[1, 2, 3, 4], [3, 5, 2, 5]])

In [72]:
arr2d[1]

array([3, 5, 2, 5])

In [73]:
arr2d[1][3]

5

In [74]:
arr2d[1, 3]

5

3D Array

In [75]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [76]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
old_values = arr3d[0].copy()

In [78]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [80]:
arr3d[0] = 42

In [81]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [82]:
arr3d[0] = old_values

In [83]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Indexing with slices

In [84]:
arr = np.arange(15)

In [85]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [86]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [87]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [88]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [91]:
arr2d[1, :2]

array([4, 5])

In [92]:
arr2d[:2,2]

array([3, 6])

In [93]:
arr2d[:2, 2]

array([3, 6])

Boolean Indexing

In [94]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [95]:
data = np.random.randn(7, 4)

In [96]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [97]:
data

array([[ 1.30273399,  1.60249802,  0.07176678, -0.79544098],
       [-1.19554445,  1.49710494, -0.44815371,  1.33208118],
       [ 0.86214095, -0.44237751, -0.18712728, -0.58027344],
       [ 0.4031226 ,  0.25601116,  0.8059078 , -0.59048655],
       [-0.15216444, -1.3317829 , -0.96583018, -0.67281829],
       [ 0.59991112, -0.33737446, -0.33277361, -0.14696936],
       [ 0.57497145,  0.62147275, -0.52387482,  0.45205988]])

In [98]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [99]:
data[names == 'Bob']

array([[ 1.30273399,  1.60249802,  0.07176678, -0.79544098],
       [ 0.4031226 ,  0.25601116,  0.8059078 , -0.59048655]])

In [100]:
data[names == 'Bob', 2:]

array([[ 0.07176678, -0.79544098],
       [ 0.8059078 , -0.59048655]])

In [101]:
data[names == 'Bob', 3]

array([-0.79544098, -0.59048655])

In [102]:
data[~(names == 'Bob')]

array([[-1.19554445,  1.49710494, -0.44815371,  1.33208118],
       [ 0.86214095, -0.44237751, -0.18712728, -0.58027344],
       [-0.15216444, -1.3317829 , -0.96583018, -0.67281829],
       [ 0.59991112, -0.33737446, -0.33277361, -0.14696936],
       [ 0.57497145,  0.62147275, -0.52387482,  0.45205988]])

In [103]:
data[names != 'Bob']

array([[-1.19554445,  1.49710494, -0.44815371,  1.33208118],
       [ 0.86214095, -0.44237751, -0.18712728, -0.58027344],
       [-0.15216444, -1.3317829 , -0.96583018, -0.67281829],
       [ 0.59991112, -0.33737446, -0.33277361, -0.14696936],
       [ 0.57497145,  0.62147275, -0.52387482,  0.45205988]])

In [104]:
data[names == 'Bob'] = 7.0

In [105]:
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [-1.19554445,  1.49710494, -0.44815371,  1.33208118],
       [ 0.86214095, -0.44237751, -0.18712728, -0.58027344],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.15216444, -1.3317829 , -0.96583018, -0.67281829],
       [ 0.59991112, -0.33737446, -0.33277361, -0.14696936],
       [ 0.57497145,  0.62147275, -0.52387482,  0.45205988]])

In [106]:
data[names != 'Bob'] = 0.0

In [107]:
data

array([[7., 7., 7., 7.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [7., 7., 7., 7.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [108]:
cond = names == 'Bob'

In [109]:
cond

array([ True, False, False,  True, False, False, False])

In [110]:
data[~cond]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Fancy Indexing 

In [111]:
arr = np.empty((8, 4))

In [112]:
for i in range(8):
    arr[i] = i

In [113]:
for i in arr:
    print(i)

[0. 0. 0. 0.]
[1. 1. 1. 1.]
[2. 2. 2. 2.]
[3. 3. 3. 3.]
[4. 4. 4. 4.]
[5. 5. 5. 5.]
[6. 6. 6. 6.]
[7. 7. 7. 7.]


In [114]:
arr[[3, 2, 7, 6]]

array([[3., 3., 3., 3.],
       [2., 2., 2., 2.],
       [7., 7., 7., 7.],
       [6., 6., 6., 6.]])

In [115]:
arr[[-1, 2, -8]]

array([[7., 7., 7., 7.],
       [2., 2., 2., 2.],
       [0., 0., 0., 0.]])

Passing Multiple Index Arrays

In [116]:
arr = np.arange(32).reshape((8, 4))

In [117]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [118]:
arr[[3, 4, 1], [3, 1, 0]]

array([15, 17,  4])

In [119]:
# NEEEED TO UNDERSTAND
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# TRANSPOSING ARRAYS AND SWAPPING AXES

In [134]:
arr = np.arange(15).reshape(3, 5)

In [135]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [137]:
a = arr.T

In [142]:
a[1:-1, 1:] = 0

In [143]:
a

array([[ 0,  5, 10],
       [ 1,  0,  0],
       [ 2,  0,  0],
       [ 3,  0,  0],
       [ 4,  9, 14]])

In [144]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  0,  0,  0,  9],
       [10,  0,  0,  0, 14]])

In [155]:
arr = np.arange(16).reshape(2, 2, 4)

In [170]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [171]:
arr.transpose(1, 0, 2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [172]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [179]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

# Universal Functions: Fast Element-Wise Array Functions

In [180]:
arr = np.arange(10)

In [181]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [182]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [183]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [188]:
a = np.random.randn(8)

In [189]:
b = np.random.randn(8)

In [190]:
a

array([-0.1498485 , -1.31018701,  1.13725829, -0.37959218,  0.75847756,
       -0.49025328,  0.09779288, -1.55568725])

In [191]:
b

array([-0.49397475, -0.79018246, -0.46121151,  0.2130278 ,  1.46585345,
       -0.18179254, -0.14440682, -1.06875995])

In [192]:
np.add(a, b)

array([-0.64382326, -2.10036947,  0.67604679, -0.16656438,  2.22433102,
       -0.67204582, -0.04661394, -2.6244472 ])

In [193]:
np.maximum(a, b)

array([-0.1498485 , -0.79018246,  1.13725829,  0.2130278 ,  1.46585345,
       -0.18179254,  0.09779288, -1.06875995])

In [194]:
arr = np.arange(10)

In [195]:
a, b = np.modf?

In [196]:
a, b = np.modf(arr)

In [197]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [198]:
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# Expressing Conditional Logic as Array Operations

In [199]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [200]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [201]:
cond = np.array([True, False, True, True, False])

In [202]:
# np.Where

In [205]:
result = np.where(cond, xarr, yarr)

In [206]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [207]:
# use of np.where

In [208]:
arr = np.random.randn(4, 4)

In [209]:
arr

array([[-0.31149452,  0.20495179, -1.15586237,  0.91869386],
       [ 0.76882168,  2.39267028,  1.38408953, -0.68407386],
       [-0.45954166, -0.73092745,  0.15045859,  0.60753771],
       [ 0.21293234, -0.46237507,  0.28959479, -0.8491185 ]])

In [210]:
arr > 0

array([[False,  True, False,  True],
       [ True,  True,  True, False],
       [False, False,  True,  True],
       [ True, False,  True, False]])

In [211]:
arr < 0

array([[ True, False,  True, False],
       [False, False, False,  True],
       [ True,  True, False, False],
       [False,  True, False,  True]])

In [212]:
result = np.where(arr > 0, 2, -2)

In [213]:
result

array([[-2,  2, -2,  2],
       [ 2,  2,  2, -2],
       [-2, -2,  2,  2],
       [ 2, -2,  2, -2]])