In [1]:
import numpy as np

# Checking Numpy Array vs Python List Efficiency

In [2]:
lst = list(range(1000000))

In [3]:
arr = np.arange(1000000)

In [4]:
# Checking Python list efficicency by multiplying each number in list by 2 10 times.
%time for i in range(10): lst2 = [p * 2 for p in lst]

Wall time: 3.13 s


In [5]:
# Checking Numpy efficicency by multiplying each number in array by 2 10 times.
%time for i in range(10): arr2 = arr * 2

Wall time: 69 ms


# Creating an array and multiplying with scalar element

In [14]:
# Generating some random data.
data = np.random.randn(2, 3)

In [15]:
data

array([[ 0.57972165,  0.65818032,  0.19082272],
       [-1.45350883, -0.94879566, -0.46194611]])

In [16]:
data * 10  # it will multiply each element in array by 10 without writing any for loop.

array([[  5.79721654,   6.58180318,   1.90822718],
       [-14.53508833,  -9.48795656,  -4.61946108]])

In [18]:
data + data   # All the element in data are added to each corresponding cell in the array.

array([[ 1.15944331,  1.31636064,  0.38164544],
       [-2.90701767, -1.89759131, -0.92389222]])

# Array Shape And Dtype

In [25]:
# Indicate how many rows and columns in the array, in this case 2 rows and 3 columns.
data.shape

(2, 3)

In [26]:
# Indicate the array data type, in this case float.
data.dtype

dtype('float64')

# Creating ndarray

In [28]:
# The easiest way to create an array is to pass list to array function.
data1 = [6, 7.5, 1, 8, 2]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 1. , 8. , 2. ])

In [30]:
# Passing nested lists of equal length will create a multidimensional array.
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
# To check is it really a multidimensional array, we use ndim.
arr2.ndim

2

In [32]:
arr2.shape

(2, 4)

# Other ways for creating ndarray or Numpy Array

In [37]:
# Creating array of zeros.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
# Pass a shape for higher dimensions.
np.zeros((2, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [40]:
# Creating array of ones.
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [48]:
data3 = np.ones((3, 2, 3))
data3

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [44]:
data3.ndim

3

In [59]:
# Creating array empty elements. -> It’s not safe to assume that np.empty will return an array of all
#zeros. In some cases, it may return uninitialized “garbage” values.
np.empty((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
# Generating series of numbers.
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [68]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Datatypes for ndarray

In [71]:
# dtype is a special object containing information about ndarray.
arr1 = np.array([1, 2, 3, 4], dtype=np.float64)

In [72]:
arr1

array([1., 2., 3., 4.])

In [78]:
arr2 = np.array([1., 2., 3., 4.], dtype=np.int32)

In [79]:
arr2

array([1, 2, 3, 4])

In [84]:
arr1.dtype

dtype('float64')

In [85]:
arr2.dtype

dtype('int32')

In [92]:
# CASTING using numpy ---- astype method ------

In [93]:
arr = np.array([1, 2, 3, 4])

In [94]:
arr.dtype

dtype('int32')

In [95]:
float_arr = arr.astype(np.float64)

In [96]:
float_arr

array([1., 2., 3., 4.])

In [97]:
float_arr.dtype

dtype('float64')

In [98]:
arr = np.array([2.3, 4.2, 5.3, 6.2, 1.9, 4.5, 1.0])

In [99]:
arr.dtype

dtype('float64')

In [100]:
int_arr = arr.astype(np.int32)

In [101]:
int_arr

array([2, 4, 5, 6, 1, 4, 1])

In [102]:
int_arr.dtype

dtype('int32')

In [103]:
# Converting Strings to floats
string_arr = np.array(['3.4', '-2.3', '4.5', '8', '3.8', '5.2', '3.7'], dtype=np.string_)

In [104]:
string_arr

array([b'3.4', b'-2.3', b'4.5', b'8', b'3.8', b'5.2', b'3.7'], dtype='|S4')

In [105]:
string_arr.dtype

dtype('S4')

In [106]:
float_arr = string_arr.astype(np.float64)

In [107]:
float_arr

array([ 3.4, -2.3,  4.5,  8. ,  3.8,  5.2,  3.7])

In [108]:
float_arr.dtype

dtype('float64')