In [1]:
import numpy as np

# Checking Numpy Array vs Python List Efficiency

In [2]:
lst = list(range(1000000))

In [3]:
arr = np.arange(1000000)

In [4]:
# Checking Python list efficicency by multiplying each number in list by 2 10 times.
%time for i in range(10): lst2 = [p * 2 for p in lst]

Wall time: 3.12 s


In [5]:
# Checking Numpy efficicency by multiplying each number in array by 2 10 times.
%time for i in range(10): arr2 = arr * 2

Wall time: 118 ms


# Creating an array and multiplying with scalar element

In [6]:
# Generating some random data.
data = np.random.randn(2, 3)

In [7]:
data

array([[-0.32985025, -1.11337713, -1.10223024],
       [-0.33373617, -0.08432006, -1.22095605]])

In [8]:
data * 10  # it will multiply each element in array by 10 without writing any for loop.

array([[ -3.29850245, -11.13377127, -11.02230239],
       [ -3.33736173,  -0.84320064, -12.20956045]])

In [9]:
data + data   # All the element in data are added to each corresponding cell in the array.

array([[-0.65970049, -2.22675425, -2.20446048],
       [-0.66747235, -0.16864013, -2.44191209]])

# Array Shape And Dtype

In [10]:
# Indicate how many rows and columns in the array, in this case 2 rows and 3 columns.
data.shape

(2, 3)

In [11]:
# Indicate the array data type, in this case float.
data.dtype

dtype('float64')

# Creating ndarray

In [12]:
# The easiest way to create an array is to pass list to array function.
data1 = [6, 7.5, 1, 8, 2]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 1. , 8. , 2. ])

In [13]:
# Passing nested lists of equal length will create a multidimensional array.
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
# To check is it really a multidimensional array, we use ndim.
arr2.ndim

2

In [15]:
arr2.shape

(2, 4)

# Other ways for creating ndarray or Numpy Array

In [16]:
# Creating array of zeros.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
# Pass a shape for higher dimensions.
np.zeros((2, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
# Creating array of ones.
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
data3 = np.ones((3, 2, 3))
data3

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [22]:
data3.ndim

3

In [24]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [25]:
# Creating array empty elements. -> It’s not safe to assume that np.empty will return an array of all
#zeros. In some cases, it may return uninitialized “garbage” values.
np.empty((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
# Generating series of numbers.
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [28]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Datatypes for ndarray

In [29]:
# dtype is a special object containing information about ndarray.
arr1 = np.array([1, 2, 3, 4], dtype=np.float64)

In [30]:
arr1

array([1., 2., 3., 4.])

In [31]:
arr2 = np.array([1., 2., 3., 4.], dtype=np.int32)

In [32]:
arr2

array([1, 2, 3, 4])

In [33]:
arr1.dtype

dtype('float64')

In [34]:
arr2.dtype

dtype('int32')

In [35]:
# CASTING using numpy ---- astype method ------

In [36]:
arr = np.array([1, 2, 3, 4])

In [37]:
arr.dtype

dtype('int32')

In [38]:
float_arr = arr.astype(np.float64)

In [39]:
float_arr

array([1., 2., 3., 4.])

In [40]:
float_arr.dtype

dtype('float64')

In [41]:
arr = np.array([2.3, 4.2, 5.3, 6.2, 1.9, 4.5, 1.0])

In [42]:
arr.dtype

dtype('float64')

In [43]:
int_arr = arr.astype(np.int32)

In [44]:
int_arr

array([2, 4, 5, 6, 1, 4, 1])

In [45]:
int_arr.dtype

dtype('int32')

In [46]:
# Converting Strings to floats
string_arr = np.array(['3.4', '-2.3', '4.5', '8', '3.8', '5.2', '3.7'], dtype=np.string_)

In [47]:
string_arr

array([b'3.4', b'-2.3', b'4.5', b'8', b'3.8', b'5.2', b'3.7'], dtype='|S4')

In [48]:
string_arr.dtype

dtype('S4')

In [49]:
float_arr = string_arr.astype(np.float64)

In [50]:
float_arr

array([ 3.4, -2.3,  4.5,  8. ,  3.8,  5.2,  3.7])

In [51]:
float_arr.dtype

dtype('float64')

# Arithematic with Numpy Arrays

In [52]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)

In [53]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [54]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [55]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [56]:
# Arithematic operations with scalar propagates scalar to each element in array.
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [57]:
arr * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [58]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [59]:
# Comparison
# Comparison between arrays of same size yields boolean arrays.

In [60]:
arr1 = np.array([[0, 4, 1], [7, 2, 12]], dtype=np.float64)

In [61]:
arr1

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [62]:
bool_arr = arr1 > arr

In [63]:
bool_arr

array([[False,  True, False],
       [ True, False,  True]])

In [64]:
bool_arr.dtype

dtype('bool')

# Indexing And Slicing

In [65]:
arr = np.arange(10)

In [66]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
arr[5]

5

In [68]:
arr[5:8]

array([5, 6, 7])

In [69]:
arr[5:8] = 12

In [70]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [71]:
# SLCING IN ARRAYS ARE VIEWS.
arr_slice = arr[5:8]

In [72]:
arr_slice

array([12, 12, 12])

In [73]:
arr_slice[1] = 12345

In [74]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [75]:
arr_slice

array([   12, 12345,    12])

HIGHER DIMENSIONS INDEXING

In [76]:
arr2d = np.array([[1, 2, 3, 4], [3, 5, 2, 5]])

In [77]:
arr2d[1]

array([3, 5, 2, 5])

In [78]:
arr2d[1][3]

5

In [79]:
arr2d[1, 3]

5

3D Array

In [80]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [81]:
arr3d.shape

(2, 2, 3)

In [82]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [83]:
old_values = arr3d[0].copy()

In [84]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [86]:
arr3d[0] = 42

In [87]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [88]:
arr3d[0] = old_values

In [89]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Indexing with slices

In [90]:
arr = np.arange(15)

In [91]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [92]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [93]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [94]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [97]:
arr2d[1, :2]

array([4, 5])

In [98]:
arr2d[:2,2]

array([3, 6])

In [99]:
arr2d[:2, 2]

array([3, 6])

Boolean Indexing

In [100]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [106]:
data = np.random.randn(7, 4)

In [107]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [108]:
data

array([[ 0.69872583, -0.69533715, -1.12765025,  1.42704792],
       [-1.04330035,  0.87364797,  0.12534168, -1.06864235],
       [ 0.68196852, -1.73146051,  0.2571116 ,  0.28198389],
       [ 0.08649114, -1.67741828,  1.89687075,  0.63732936],
       [ 0.51430844, -0.71725631,  0.64952846, -0.58181428],
       [-0.51248142,  0.32135655, -0.15677038,  0.6083305 ],
       [ 0.78275623, -1.5918926 ,  0.44268264,  0.40898625]])

In [109]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [113]:
data[names == 'Bob']

array([[ 0.69872583, -0.69533715, -1.12765025,  1.42704792],
       [ 0.08649114, -1.67741828,  1.89687075,  0.63732936]])

In [114]:
data[names == 'Bob', 2:]

array([[-1.12765025,  1.42704792],
       [ 1.89687075,  0.63732936]])

In [115]:
data[names == 'Bob', 3]

array([1.42704792, 0.63732936])

In [116]:
data[~(names == 'Bob')]

array([[-1.04330035,  0.87364797,  0.12534168, -1.06864235],
       [ 0.68196852, -1.73146051,  0.2571116 ,  0.28198389],
       [ 0.51430844, -0.71725631,  0.64952846, -0.58181428],
       [-0.51248142,  0.32135655, -0.15677038,  0.6083305 ],
       [ 0.78275623, -1.5918926 ,  0.44268264,  0.40898625]])

In [117]:
data[names != 'Bob']

array([[-1.04330035,  0.87364797,  0.12534168, -1.06864235],
       [ 0.68196852, -1.73146051,  0.2571116 ,  0.28198389],
       [ 0.51430844, -0.71725631,  0.64952846, -0.58181428],
       [-0.51248142,  0.32135655, -0.15677038,  0.6083305 ],
       [ 0.78275623, -1.5918926 ,  0.44268264,  0.40898625]])

In [118]:
data[names == 'Bob'] = 7.0

In [119]:
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [-1.04330035,  0.87364797,  0.12534168, -1.06864235],
       [ 0.68196852, -1.73146051,  0.2571116 ,  0.28198389],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.51430844, -0.71725631,  0.64952846, -0.58181428],
       [-0.51248142,  0.32135655, -0.15677038,  0.6083305 ],
       [ 0.78275623, -1.5918926 ,  0.44268264,  0.40898625]])

In [120]:
data[names != 'Bob'] = 0.0

In [121]:
data

array([[7., 7., 7., 7.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [7., 7., 7., 7.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [122]:
cond = names == 'Bob'

In [123]:
cond

array([ True, False, False,  True, False, False, False])

In [124]:
data[~cond]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Fancy Indexing 

In [125]:
arr = np.empty((8, 4))

In [126]:
for i in range(8):
    arr[i] = i

In [127]:
for i in arr:
    print(i)

[0. 0. 0. 0.]
[1. 1. 1. 1.]
[2. 2. 2. 2.]
[3. 3. 3. 3.]
[4. 4. 4. 4.]
[5. 5. 5. 5.]
[6. 6. 6. 6.]
[7. 7. 7. 7.]


In [128]:
arr[[3, 2, 7, 6]]

array([[3., 3., 3., 3.],
       [2., 2., 2., 2.],
       [7., 7., 7., 7.],
       [6., 6., 6., 6.]])

In [129]:
arr[[-1, 2, -8]]

array([[7., 7., 7., 7.],
       [2., 2., 2., 2.],
       [0., 0., 0., 0.]])

Passing Multiple Index Arrays

In [130]:
arr = np.arange(32).reshape((8, 4))

In [131]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [132]:
arr[[3, 4, 1], [3, 1, 0]]

array([15, 17,  4])

In [133]:
# NEEEED TO UNDERSTAND
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# TRANSPOSING ARRAYS AND SWAPPING AXES

In [134]:
arr = np.arange(15).reshape(3, 5)

In [135]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [136]:
a = arr.T

In [140]:
a

array([[ 0,  5, 10],
       [ 1,  0,  0],
       [ 2,  0,  0],
       [ 3,  0,  0],
       [ 4,  9, 14]])

In [141]:
a[1:-1, 1:] = 0

In [142]:
a

array([[ 0,  5, 10],
       [ 1,  0,  0],
       [ 2,  0,  0],
       [ 3,  0,  0],
       [ 4,  9, 14]])

In [143]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  0,  0,  0,  9],
       [10,  0,  0,  0, 14]])

In [144]:
arr = np.arange(16).reshape(2, 2, 4)

In [145]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [146]:
arr.transpose(1, 0, 2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [147]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [148]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

# Universal Functions: Fast Element-Wise Array Functions

In [149]:
arr = np.arange(10)

In [150]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [151]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [152]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [153]:
a = np.random.randn(8)

In [154]:
b = np.random.randn(8)

In [155]:
a

array([ 0.47692289,  0.56880318,  0.09604365,  1.06143558,  0.47325113,
        0.61658149, -0.4457148 , -0.56017411])

In [156]:
b

array([-0.20838324,  0.09112338, -1.37972511,  0.29291489, -0.5712919 ,
        0.07650027, -0.26147073,  2.36126954])

In [157]:
np.add(a, b)

array([ 0.26853965,  0.65992655, -1.28368146,  1.35435048, -0.09804077,
        0.69308176, -0.70718553,  1.80109544])

In [158]:
np.maximum(a, b)

array([ 0.47692289,  0.56880318,  0.09604365,  1.06143558,  0.47325113,
        0.61658149, -0.26147073,  2.36126954])

In [159]:
arr = np.arange(10)

In [160]:
a, b = np.modf?

In [ ]:
a, b = np.modf

In [161]:
a, b = np.modf

TypeError: cannot unpack non-iterable numpy.ufunc object

In [162]:
a, b = np.modf(arr)

In [163]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [164]:
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# Expressing Conditional Logic as Array Operations

In [165]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [166]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [167]:
cond = np.array([True, False, True, True, False])

In [168]:
# np.Where

In [169]:
result = np.where(cond, xarr, yarr)

In [170]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [171]:
# use of np.where

In [172]:
arr = np.random.randn(4, 4)

In [173]:
arr

array([[-0.22315923, -0.88421849,  0.22360434,  0.01178641],
       [-0.32659055,  1.73957307, -0.43913652, -0.47004592],
       [-0.59398435,  0.70016318,  0.38112216, -1.42753128],
       [ 1.29089203,  0.80862755, -0.0252645 ,  0.42710021]])

In [174]:
arr > 0

array([[False, False,  True,  True],
       [False,  True, False, False],
       [False,  True,  True, False],
       [ True,  True, False,  True]])

In [175]:
arr < 0

array([[ True,  True, False, False],
       [ True, False,  True,  True],
       [ True, False, False,  True],
       [False, False,  True, False]])

In [176]:
result = np.where(arr > 0, 2, -2)

In [177]:
result

array([[-2, -2,  2,  2],
       [-2,  2, -2, -2],
       [-2,  2,  2, -2],
       [ 2,  2, -2,  2]])

# Mathematical and Statistical methods

In [178]:
arr = np.random.randn(5, 4)

In [179]:
arr

array([[ 1.04715119e+00, -8.85642362e-01, -7.81223889e-04,
        -4.58594304e-01],
       [ 1.27247275e+00,  4.91233303e-01,  5.91168231e-01,
         7.54553043e-01],
       [ 1.48922758e+00, -1.28816782e+00, -3.10087190e-01,
        -8.70571632e-01],
       [-8.47528989e-01, -6.21437245e-01, -2.99663296e+00,
         7.08331687e-01],
       [-5.19582720e-01, -1.82480647e-01, -2.27813068e+00,
        -1.39329180e+00]])

In [180]:
np.sum(arr)

-6.298791784372535

In [181]:
a = np.arange(10).reshape(5, 2)

In [182]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [183]:
np.mean(a)

4.5

In [184]:
arr

array([[ 1.04715119e+00, -8.85642362e-01, -7.81223889e-04,
        -4.58594304e-01],
       [ 1.27247275e+00,  4.91233303e-01,  5.91168231e-01,
         7.54553043e-01],
       [ 1.48922758e+00, -1.28816782e+00, -3.10087190e-01,
        -8.70571632e-01],
       [-8.47528989e-01, -6.21437245e-01, -2.99663296e+00,
         7.08331687e-01],
       [-5.19582720e-01, -1.82480647e-01, -2.27813068e+00,
        -1.39329180e+00]])

In [185]:
np.mean(arr)

-0.31493958921862675

In [186]:
np.std(a)

2.8722813232690143

In [187]:
np.var(a)

8.25

In [188]:
np.min(a)

0

In [189]:
np.max(a)

9

In [190]:
np.min(arr)

-2.9966329615616263

In [191]:
np.max(arr)

1.4892275832511535

In [192]:
np.argmin(a)

0

In [193]:
np.argmax(a)

9

In [194]:
np.argmin(arr)

14

In [195]:
np.argmax(arr)

8

In [196]:
np.cumsum(a)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [197]:
np.cumsum(arr)

array([ 1.04715119,  0.16150883,  0.1607276 , -0.2978667 ,  0.97460605,
        1.46583935,  2.05700758,  2.81156063,  4.30078821,  3.01262039,
        2.7025332 ,  1.83196157,  0.98443258,  0.36299534, -2.63363762,
       -1.92530594, -2.44488866, -2.62736931, -4.90549998, -6.29879178])

In [198]:
np.cumprod(a)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [199]:
np.cumprod(arr)

array([ 1.04715119e+00, -9.27401452e-01,  7.24508169e-04, -3.32255319e-04,
       -4.22785840e-04, -2.07686485e-04, -1.22777652e-04, -9.26422506e-05,
       -1.37965395e-04,  1.77722582e-04, -5.51094961e-05,  4.79767639e-05,
       -4.06616982e-05,  2.52686937e-05, -7.57210004e-05, -5.36355839e-05,
        2.78681226e-05, -5.08539304e-06,  1.15851899e-05, -1.61415501e-05])

In [200]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [201]:
np.sum(a, axis=0)

array([20, 25])

In [202]:
np.mean(arr, 1)

array([-0.07446668,  0.77735683, -0.24489976, -0.93931688, -1.09337146])

In [203]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [204]:
a.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [205]:
a.cumsum(1)

array([[ 0,  1],
       [ 2,  5],
       [ 4,  9],
       [ 6, 13],
       [ 8, 17]], dtype=int32)

In [206]:
a.sum(0)

array([20, 25])

In [207]:
np.sum(a, axis=1)

array([ 1,  5,  9, 13, 17])

In [208]:
a.sum(0)

array([20, 25])

In [209]:
a.mean(1)

array([0.5, 2.5, 4.5, 6.5, 8.5])

# Methods for Boolean Arrays

In [210]:
arr = np.random.randn(100)

In [211]:
arr

array([ 0.36641829,  0.87061424, -0.03255939,  1.39929606, -0.60964323,
       -0.100072  , -2.17182335, -0.65950993, -1.27423919,  0.25976169,
        1.60866838, -0.38677313, -0.57132018, -0.59495799,  0.69611639,
        1.28222589,  0.75915448, -0.51884694, -0.13663156, -0.49821821,
        1.6857524 ,  0.78217531, -0.46163028, -0.26032261,  1.02569585,
       -0.34911245,  0.05870286,  0.23862406, -0.87260368, -1.14612969,
       -0.30056317, -0.97388207, -2.18853982,  0.32673266,  0.09562804,
        0.75709802, -1.07966863,  1.39312812,  1.2677238 , -1.32169629,
        0.01139449,  0.73094205,  1.10266927,  1.23237754, -0.59414783,
       -0.89787652, -0.45963491,  0.57249103,  0.44809979, -0.75337236,
        1.30833066, -0.19843258, -0.89302395, -2.26643207, -0.63153871,
       -1.18441683, -1.99610804,  0.42687731,  0.14669852, -0.17604265,
        1.11630544, -1.15672791,  0.46202129,  1.6278537 , -0.80200757,
        1.41045848,  0.11698816,  1.52341273, -0.17500217,  1.67

In [212]:
b = arr[arr > 0]

In [213]:
len(b)

47

In [216]:
arr[arr > 0].sum()

37.095186400807755

In [217]:
(arr > 0).sum()

47

In [218]:
arr[arr > 0].sum()

37.095186400807755

In [219]:
a = np.array([3, 4, -2, 2, 1, 4, -2])

In [220]:
a

array([ 3,  4, -2,  2,  1,  4, -2])

In [221]:
a > 0

array([ True,  True, False,  True,  True,  True, False])

In [222]:
a[a > 0]

array([3, 4, 2, 1, 4])

In [223]:
a[a > 0].sum()

14

In [224]:
(a > 0).sum()

5

In [225]:
(a > 0).any()

True

In [226]:
(a > 0).all()

False

Sorting

In [227]:
arr = np.array([4, 2, 1, 0, 6, 3])

In [228]:
arr

array([4, 2, 1, 0, 6, 3])

In [229]:
arr.sort()

In [230]:
arr

array([0, 1, 2, 3, 4, 6])

In [231]:
a = np.random.randn(5, 3)

In [232]:
a

array([[ 0.25266873, -0.84507367, -1.16924914],
       [-0.79893983, -0.1654323 ,  1.64184652],
       [-0.09817532,  0.89493926, -0.6295271 ],
       [-0.30552531, -0.07355799,  0.11048251],
       [-0.49850771,  0.4871117 ,  0.70840279]])

In [233]:
a.sort(0)

In [234]:
a

array([[-0.79893983, -0.84507367, -1.16924914],
       [-0.49850771, -0.1654323 , -0.6295271 ],
       [-0.30552531, -0.07355799,  0.11048251],
       [-0.09817532,  0.4871117 ,  0.70840279],
       [ 0.25266873,  0.89493926,  1.64184652]])

# Unique and Other Set Logic

In [235]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [236]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [237]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [238]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [239]:
ints

array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [240]:
np.unique(ints)

array([1, 2, 3, 4])

In [241]:
arr = np.arange(15)

# File Input and Output with Arrays

In [242]:
np.save('testarray', arr)

In [243]:
np.load('testarray.npy')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Linear Algebra

In [244]:
a = np.arange(1, 7).reshape(2, 3)

In [245]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [246]:
b = np.array([[6, 23], [-1, 7], [8, 9]])

In [247]:
b

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [248]:
np.dot(a, b)

array([[ 28,  64],
       [ 67, 181]])

matrix product between a two-dimensional array and a suitably sized onedimensional
array results in a one-dimensional array

In [249]:
np.dot(a, np.ones(3))

array([ 6., 15.])

In [250]:
np.ones(3)

array([1., 1., 1.])

In [251]:
a @ b

array([[ 28,  64],
       [ 67, 181]])

numpy.linalg 

In [252]:
from numpy.linalg import inv, qr, det

In [253]:
X = np.arange(1, 26).reshape(5, 5)

In [254]:
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [255]:
mat = X.T.dot(X)

In [256]:
mat

array([[ 855,  910,  965, 1020, 1075],
       [ 910,  970, 1030, 1090, 1150],
       [ 965, 1030, 1095, 1160, 1225],
       [1020, 1090, 1160, 1230, 1300],
       [1075, 1150, 1225, 1300, 1375]])

In [257]:
inv(mat)

array([[-1.61261705e+13,  8.79609302e+12,  1.68591783e+13,
         4.39804651e+12, -1.39271473e+13],
       [ 1.46601550e+13, -8.79609302e+12, -1.61261705e+13,
         3.35937500e-03,  1.02621085e+13],
       [ 5.86406201e+12, -0.00000000e+00, -7.33007752e+12,
        -8.79609302e+12,  1.02621085e+13],
       [ 8.79609302e+12, -8.79609302e+12, -4.39804651e+12,
        -0.00000000e+00,  4.39804651e+12],
       [-1.31941395e+13,  8.79609302e+12,  1.09951163e+13,
         4.39804651e+12, -1.09951163e+13]])

In [258]:
mat.dot(inv(mat))

array([[ 2.,  0., -4., -1.,  0.],
       [ 4.,  0., -4.,  0.,  2.],
       [ 4.,  0., -4., -1.,  4.],
       [ 2.,  0., -2., -1.,  4.],
       [ 0.,  0., -2.,  0.,  4.]])

In [259]:
q, r = qr(mat)

In [260]:
r

array([[-2.16480369e+03, -2.31094858e+03, -2.45709347e+03,
        -2.60323836e+03, -2.74938325e+03],
       [ 0.00000000e+00,  4.08297289e+00,  8.16594578e+00,
         1.22489187e+01,  1.63318916e+01],
       [ 0.00000000e+00,  0.00000000e+00, -1.26658883e-13,
        -1.15882484e-13, -1.43937555e-13],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         2.97663078e-13,  2.72066977e-13],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -1.07281270e-13]])

In [261]:
# diag

In [262]:
a = np.eye(5, 5)

In [263]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [264]:
b = np.diag(a)

In [265]:
b

array([1., 1., 1., 1., 1.])

In [266]:
np.diag(b)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [267]:
# trace

In [268]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [269]:
np.trace(a)

5.0

In [270]:
det(a)

1.0

# Pseudorandom Number Generation

In [271]:
samples = np.random.normal(size=(4, 4))

In [272]:
samples

array([[-0.8096888 , -0.34707796, -1.42875888, -0.09896024],
       [-1.18412942,  0.96011743, -0.48189727, -1.04997684],
       [-0.11633748,  0.30944591,  1.34314145, -0.11541826],
       [-0.28900587,  2.0214638 , -0.96894449, -0.53691457]])

# Python Built-in random module vs numpy.random module

In [273]:
from random import normalvariate

In [274]:
N = 1000000

In [275]:
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

3.3 s ± 290 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [276]:
%timeit np.random.normal(size=N)

73.1 ms ± 21 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
