In [1]:
import numpy as np

# Checking Numpy Array vs Python List Efficiency

In [2]:
lst = list(range(1000000))

In [3]:
arr = np.arange(1000000)

In [4]:
# Checking Python list efficicency by multiplying each number in list by 2 10 times.
%time for i in range(10): lst2 = [p * 2 for p in lst]

Wall time: 3.26 s


In [5]:
# Checking Numpy efficicency by multiplying each number in array by 2 10 times.
%time for i in range(10): arr2 = arr * 2

Wall time: 71.1 ms


# Creating an array and multiplying with scalar element

In [6]:
# Generating some random data.
data = np.random.randn(2, 3)

In [7]:
data

array([[-0.29778967, -2.40208356,  0.33344503],
       [ 1.3046448 , -0.35907398, -2.57392729]])

In [8]:
data * 10  # it will multiply each element in array by 10 without writing any for loop.

array([[ -2.97789667, -24.02083561,   3.33445029],
       [ 13.04644801,  -3.59073981, -25.73927287]])

In [9]:
data + data   # All the element in data are added to each corresponding cell in the array.

array([[-0.59557933, -4.80416712,  0.66689006],
       [ 2.6092896 , -0.71814796, -5.14785457]])

# Array Shape And Dtype

In [10]:
# Indicate how many rows and columns in the array, in this case 2 rows and 3 columns.
data.shape

(2, 3)

In [11]:
# Indicate the array data type, in this case float.
data.dtype

dtype('float64')

# Creating ndarray

In [12]:
# The easiest way to create an array is to pass list to array function.
data1 = [6, 7.5, 1, 8, 2]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 1. , 8. , 2. ])

In [13]:
# Passing nested lists of equal length will create a multidimensional array.
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
# To check is it really a multidimensional array, we use ndim.
arr2.ndim

2

In [15]:
arr2.shape

(2, 4)

# Other ways for creating ndarray or Numpy Array

In [16]:
# Creating array of zeros.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
# Pass a shape for higher dimensions.
np.zeros((2, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
# Creating array of ones.
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
data3 = np.ones((3, 2, 3))
data3

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [20]:
data3.ndim

3

In [21]:
# Creating array empty elements. -> It’s not safe to assume that np.empty will return an array of all
#zeros. In some cases, it may return uninitialized “garbage” values.
np.empty((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
# Generating series of numbers.
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Datatypes for ndarray

In [24]:
# dtype is a special object containing information about ndarray.
arr1 = np.array([1, 2, 3, 4], dtype=np.float64)

In [25]:
arr1

array([1., 2., 3., 4.])

In [26]:
arr2 = np.array([1., 2., 3., 4.], dtype=np.int32)

In [27]:
arr2

array([1, 2, 3, 4])

In [28]:
arr1.dtype

dtype('float64')

In [29]:
arr2.dtype

dtype('int32')

In [30]:
# CASTING using numpy ---- astype method ------

In [31]:
arr = np.array([1, 2, 3, 4])

In [32]:
arr.dtype

dtype('int32')

In [33]:
float_arr = arr.astype(np.float64)

In [34]:
float_arr

array([1., 2., 3., 4.])

In [35]:
float_arr.dtype

dtype('float64')

In [36]:
arr = np.array([2.3, 4.2, 5.3, 6.2, 1.9, 4.5, 1.0])

In [37]:
arr.dtype

dtype('float64')

In [38]:
int_arr = arr.astype(np.int32)

In [39]:
int_arr

array([2, 4, 5, 6, 1, 4, 1])

In [40]:
int_arr.dtype

dtype('int32')

In [41]:
# Converting Strings to floats
string_arr = np.array(['3.4', '-2.3', '4.5', '8', '3.8', '5.2', '3.7'], dtype=np.string_)

In [42]:
string_arr

array([b'3.4', b'-2.3', b'4.5', b'8', b'3.8', b'5.2', b'3.7'], dtype='|S4')

In [43]:
string_arr.dtype

dtype('S4')

In [44]:
float_arr = string_arr.astype(np.float64)

In [45]:
float_arr

array([ 3.4, -2.3,  4.5,  8. ,  3.8,  5.2,  3.7])

In [46]:
float_arr.dtype

dtype('float64')

# Arithematic with Numpy Arrays

In [55]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)

In [56]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [57]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [58]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [60]:
# Arithematic operations with scalar propagates scalar to each element in array.
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [61]:
arr * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [62]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [63]:
# Comparison
# Comparison between arrays of same size yields boolean arrays.

In [64]:
arr1 = np.array([[0, 4, 1], [7, 2, 12]], dtype=np.float64)

In [65]:
arr1

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [68]:
bool_arr = arr1 > arr

In [70]:
bool_arr

array([[False,  True, False],
       [ True, False,  True]])

In [71]:
bool_arr.dtype

dtype('bool')

# Indexing And Slicing

In [115]:
arr = np.arange(10)

In [116]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
arr[5]

5

In [118]:
arr[5:8]

array([5, 6, 7])

In [119]:
arr[5:8] = 12

In [120]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [121]:
# SLCING IN ARRAYS ARE VIEWS.
arr_slice = arr[5:8]

In [122]:
arr_slice

array([12, 12, 12])

In [123]:
arr_slice[1] = 12345

In [124]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [125]:
arr_slice

array([   12, 12345,    12])

HIGHER DIMENSIONS INDEXING

In [126]:
arr2d = np.array([[1, 2, 3, 4], [3, 5, 2, 5]])

In [128]:
arr2d[1]

array([3, 5, 2, 5])

In [130]:
arr2d[1][3]

5

In [131]:
arr2d[1, 3]

5

In [136]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [140]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [148]:
arr3d[0]

5